Config = {}

Config.rackableWeapons = {
    ['WEAPON_PISTOL'] = {offset = {z = 0.1}, type = 'pistol'},
    ['WEAPON_PISTOL_MK2'] = {offset = {z = 0.1}, type = 'pistol'},
    ['WEAPON_COMBATPISTOL'] = {offset = {z = 0.1}, type = 'pistol'},
    ['WEAPON_APPISTOL'] = {offset = {z = 0.1}, type = 'pistol'},
    ['WEAPON_PISTOL50'] = {offset = {z = 0.1}, type = 'pistol'},
    ['WEAPON_SNSPISTOL'] = {offset = {z = 0.1}, type = 'pistol'},
    ['WEAPON_SNSPISTOL_MK2'] = {offset = {z = 0.1}, type = 'pistol'},
    ['WEAPON_HEAVYPISTOL'] = {offset = {z = 0.1}, type = 'pistol'},
    ['WEAPON_VINTAGEPISTOL'] = {offset = {z = 0.1}, type = 'pistol'},
    ['WEAPON_MARKSMANPISTOL'] = {offset = {z = 0.1}, type = 'pistol'},
    ['WEAPON_REVOLVER'] = {offset = {z = 0.1}, type = 'pistol'},
    ['WEAPON_REVOLVER_MK2'] = {offset = {z = 0.1}, type = 'pistol'},
    ['WEAPON_DOUBLEACTION'] = {offset = {z = 0.1}, type = 'pistol'},
    ['WEAPON_MICROSMG'] = {offset = {z = 0.1}, type = 'smg'},
    ['WEAPON_SMG'] = {offset = {z = 0.65}, type = 'smg'},
    ['WEAPON_SMG_MK2'] = {offset = {z = 0.65}, type = 'smg'},
    ['WEAPON_ASSAULTSMG'] = {offset = {y = 0.1, z = 0.75}, type = 'smg'},
    ['WEAPON_COMBATPDW'] = {offset = {z = 0.1}, type = 'smg'},
    ['WEAPON_MACHINEPISTOL'] = {offset = {z = 0.1}, type = 'smg'},
    ['WEAPON_MINISMG'] = {offset = {z = 0.50}, type = 'smg'},
    ['WEAPON_ASSAULTRIFLE'] = {offset = {z = 0.65}, type = 'rifle'},
    ['WEAPON_ASSAULTRIFLE_MK2'] = {offset = {z = 0.65}, type = 'rifle'},
    ['WEAPON_CARBINERIFLE'] = {offset = {z = 0.60}, type = 'rifle'},
    ['WEAPON_CARBINERIFLE_MK2'] = {offset = {z = 0.68}, type = 'rifle'},
    ['WEAPON_ADVANCEDRIFLE'] = {offset = {z = 0.77}, type = 'rifle'},
    ['WEAPON_SPECIALCARBINE'] = {offset = {z = 0.7}, type = 'rifle'},
    ['WEAPON_BULLPUPRIFLE'] = {offset = {z = 0.80}, type = 'rifle'},
    ['WEAPON_BULLPUPRIFLE_MK2'] = {offset = {z = 0.67}, type = 'rifle'},
    ['WEAPON_COMPACTRIFLE'] = {offset = {z = 0.1}, type = 'rifle'},
    ['WEAPON_MG'] = {offset = {z = 0.6}, type = 'mg'},
    ['WEAPON_COMBATMG'] = {offset = {z = 0.7}, type = 'mg'},
    ['WEAPON_COMBATMG_MK2'] = {offset = {z = 0.1}, type = 'mg'},
    ['WEAPON_GUSENBERG'] = {offset = {z = 0.68}, type = 'mg'},
    ['WEAPON_SNIPERRIFLE'] = {offset = {z = 0.72}, type = 'sniper'},
    ['WEAPON_HEAVYSNIPER'] = {offset = {z = 0.72}, type = 'sniper'},
    ['WEAPON_MARKSMANRIFLE'] = {offset = {z = 0.72}, type = 'sniper'},
    ['WEAPON_MARKSMANRIFLE_MK2'] = {offset = {z = 0.72}, type = 'sniper'},
    -- ['WEAPON_RPG'] = {label = 'RPG', model = 'w_lr_rpg', offset = {z = 0.1}},
    -- ['WEAPON_GRENADELAUNCHER'] = {label = 'Grenade Launcher', model = 'w_lr_grenadelauncher', offset = {z = 0.1}},
    -- ['WEAPON_GRENADELAUNCHER_SMOKE'] = {label = 'Smoke Grenade Launcher', model = 'w_lr_grenadelaunchersmoke', offset = {z = 0.1}},
    -- ['WEAPON_MINIGUN'] = {label = 'Minigun', model = 'w_mg_minigun', offset = {z = 0.1}},
    -- ['WEAPON_FIREWORK'] = {label = 'Firework Launcher', model = 'w_lr_firework', offset = {z = 0.1}},
    -- ['WEAPON_RAILGUN'] = {label = 'Railgun', model = 'w_ar_railgun', offset = {z = 0.1}},
}